twig:
#    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_horizontal_layout.html.twig' ]
    globals:
        image_url: '%env(resolve:IMAGE_URL)%'
when@test:
    twig:
        strict_variables: true
