version: '3'

services:
  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2231
    volumes:
      - mysql-storage:/var/lib/mysql

  redis:
    container_name: redis
    image: redis

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq

  app:
    container_name: app
    build:
      context: ./
      target: start
    volumes:
      - ../:/var/www/project
    environment:
      WEB_SERVER_HOST: 'nginx'
      DATABASE_URL: 'mysql://root:2231@db:3306/secondDB?serverVersion=8.0'
      REDIS_DSN: 'redis://redis:6379'
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
    links:
      - db
      - redis
      - rabbitmq

  consume:
    container_name: consume
    build:
      context: ./
      target: consume
    volumes:
      - ../:/var/www/project
    environment:
      DATABASE_URL: 'mysql://root:2231@db:3306/secondDB?serverVersion=8.0'
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
    links:
      - app
    restart: always

  node:
    container_name: node
    build:
      context: ./
      target: node
    volumes:
      - ../:/var/www/project
    links:
      - app

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ../public:/var/www/project/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

volumes:
  mysql-storage:
