controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

login:
    path: /login
    controller: App\Controller\LoginController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::register

verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

admin_user_list:
    path: /admin/user/list
    controller: App\Controller\UserController::index

admin_add_user:
    path: /admin/user/add
    controller: App\Controller\UserController::createAndUpdate

admin_edit_user:
    path: /admin/user/edit/{id<\d+>}
    controller: App\Controller\UserController::createAndUpdate

admin_delete_user:
    path: /admin/user/delete/{id<\d+>}
    controller: App\Controller\UserController::delete

manager_products_list:
    path: /manager/products/list
    controller: App\Controller\ProductsController::index

manager_add_products:
    path: /manager/products/add
    controller: App\Controller\ProductsController::createAndUpdate

manager_edit_products:
    path: /manager/products/edit/{id<\d+>}
    controller: App\Controller\ProductsController::createAndUpdate

manager_delete_products:
    path: /manager/products/delete/{id<\d+>}
    controller: App\Controller\ProductsController::delete

manager_add_category:
    path: /manager/category/add
    controller: App\Controller\CategoriesController::createAndUpdate

store_list:
    path: /store/list
    controller: App\Controller\StoreController::index

store_product:
    path: /store/product/{id<\d+>}
    controller: App\Controller\StoreController::getOneProduct