controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

login:
    path: /login
    controller: App\Controller\LoginController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::register


verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

#//Admin Routes
admin_user_list:
    path: /admin/user/list
    controller: App\Controller\UserController::index

admin_add_user:
    path: /admin/user/add
    controller: App\Controller\UserController::create

admin_edit_user:
    path: /admin/user/edit/{id<\d+>}
    controller: App\Controller\UserController::update

admin_delete_user:
    path: /admin/user/delete/{id<\d+>}
    controller: App\Controller\UserController::delete

#//Manager Routes
manager_products_list:
    path: /manager/products/list
    controller: App\Controller\ProductsController::index

manager_add_products:
    path: /manager/products/add
    controller: App\Controller\ProductsController::createAndUpdate

manager_edit_products:
    path: /manager/products/edit/{id<\d+>}
    controller: App\Controller\ProductsController::createAndUpdate
    options:
        expose: true

manager_delete_products:
    path: /manager/products/delete/{id<\d+>}
    controller: App\Controller\ProductsController::delete
    options:
        expose: true

manager_list_category:
    path: /manager/category/list
    controller: App\Controller\CategoriesController::index

manager_add_category:
    path: /manager/category/add
    controller: App\Controller\CategoriesController::createAndUpdate

manager_edit_category:
    path: /manager/category/edit/{id<\d+>}
    controller: App\Controller\CategoriesController::createAndUpdate

manager_delete_category:
    path: /manager/category/delete/{id<\d+>}
    controller: App\Controller\CategoriesController::delete

#//Store Routes
store_list:
    path: /store/list
    controller: App\Controller\StoreController::index

store_product_category:
    path: /store/{slug?}
    controller: App\Controller\StoreController::index

store_product:
    path: /store/{slug}/{id<\d+>}
    controller: App\Controller\StoreController::productPage

#Cart Routes

cart:
    path: /cart/
    controller: App\Controller\OrdersController::cart

cart_remove:
    path: /cart/remove/{id<\d+>?}
    controller: App\Controller\OrdersController::deleteFromCart


#Order Routes
order_list:
    path: /orders/
    controller: App\Controller\OrdersController::orders

order:
    path: /orders/order/{id}
    controller: App\Controller\OrdersController::order

order_create:
    path: cart/order/create
    controller: App\Controller\OrdersController::createOrder

#API Product
product_index:
    path: api/products
    controller: App\Controller\API\ProductController::index
    methods: GET
    options:
        expose: true

product_show:
    path: api/products/{id<\d+>}
    controller: App\Controller\API\ProductController::show
    methods: GET
    options:
        expose: true

product_add:
    path: api/products
    controller: App\Controller\API\ProductController::add
    methods: POST
    options:
        expose: true

product_edit:
    path: api/products/{id<\d+>}
    controller: App\Controller\API\ProductController::edit
    methods: PUT

product_delete:
    path: api/products/{id<\d+>}
    controller: App\Controller\API\ProductController::delete
    methods: DELETE

product_create:
    path: api/images
    controller: App\Controller\API\ImageController::create
    methods: POST
    options:
        expose: true

#API Service
service_index:
    path: api/services
    controller: App\Controller\API\ServiceController::index
    methods: GET
    options:
        expose: true

service_show:
    path: api/services/{id<\d+>}
    controller: App\Controller\API\ServiceController::show
    methods: GET
    options:
        expose: true

service_add:
    path: api/services
    controller: App\Controller\API\ServiceController::add
    methods: POST
    options:
        expose: true

service_edit:
    path: api/services/{id<\d+>}
    controller: App\Controller\API\ServiceController::edit
    methods: PUT

service_delete:
    path: api/services/{id<\d+>}
    controller: App\Controller\API\ServiceController::delete
    methods: DELETE